---
include:
  # process first
  - "config/annotations*.rb"
  - "**/*.rb"
  - "**/.*.rb"
  - "lib/tasks/*.rake"
  - ".git-hooks/**/*.rb"
  - "script/*"
  - "bin/*"
  - "bin/overcommit_branch"
exclude:
  - script/.rubocop.yml
  - vendor/**/*
  - spec/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck:strong
  - update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
